Lab01Ak/Controllers/BirthController.cs
using Lab01Ak.Models;
using Microsoft.AspNetCore.Mvc;

namespace LaboratoriumASPNET.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result([FromForm]Birth model)
        {
            if(!model.IsValid())
            {
                return View("Error", model);
            }

            return View(model);
        }

        public IActionResult Form() 
        {
            return View();
        }
    }
}

Lab01Ak/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lab01Ak.Models.Controllers;

public class CalculatorController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
    
    public enum Operator
    {
        Unknown, Add, Mul, Sub, Div
    }
    [HttpPost]
    public IActionResult Result([FromForm]Calculator model)
    {
        if (!model.IsValid())
        {
            return View("Error");
        }
        return View(model);
    }
            public IActionResult Form()
            {
                return View();
            }
        }

Lab01Ak/Controllers/ContactController.cs
using Lab01Ak.Models;
using LaboratoriumASPNET.Models.Services;
using Microsoft.AspNetCore.Mvc;

namespace LaboratoriumASPNET.Controllers;

public class ContactController : Controller
{
    private readonly IContactService _contactService;

    // Konstruktor z wstrzykiwaniem zależności
    public ContactController(IContactService contactService)
    {
        _contactService = contactService;
    }

    // Lista kontaktów
    public IActionResult Index()
    {
        // Przekazujemy listę kontaktów do widoku
        return View(_contactService.GetAll());
    }
    
    // Formularz dodania kontaktu
    public IActionResult Add()
    {
        return View();
    }

    // Odebranie danych z formularza i zapisanie w kontaktach
    [HttpPost]
    public IActionResult Add(ContactModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        _contactService.Add(model);

        // Przekierowanie do listy kontaktów po dodaniu nowego kontaktu
        return RedirectToAction("Index");
    }

    // Usunięcie kontaktu
    public IActionResult Delete(int id)
    {
        _contactService.Delete(id);

        // Przekierowanie do listy kontaktów po usunięciu kontaktu
        return RedirectToAction("Index");
    }

    // Szczegóły kontaktu
    public IActionResult Details(int id)
    {
        var contact = _contactService.GetById(id);
        if (contact == null)
        {
            return NotFound();
        }
        return View(contact);
    }
    
    // Formularz edycji kontaktu
    public IActionResult Edit(int id)
    {
        var contact = _contactService.GetById(id);
        if (contact == null)
        {
            return NotFound();
        }
        
        return View(contact);
    }

    // POST: Zapisz zmiany kontaktu
    [HttpPost]
    public IActionResult Edit(ContactModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        _contactService.Update(model);
        return RedirectToAction("Index");
    }
}

Lab01Ak/Controllers/EmployeeController.cs
using Lab01Ak.Models;
using Microsoft.AspNetCore.Mvc;

public class EmployeeController : Controller
{
    static Dictionary<int, Employee> _employees = new Dictionary<int, Employee>();

    public IActionResult Index()
    {
        return View(_employees);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Employee model)
    {
        if (ModelState.IsValid)
        {
            int id = _employees.Count > 0 ? _employees.Keys.Max() + 1 : 1;
            model.Id = id;
            _employees.Add(model.Id, model);
            return RedirectToAction("Index");
        }
        return View(model);
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        if (_employees.ContainsKey(id))
        {
            return View(_employees[id]);
        }
        return NotFound();
    }

    [HttpPost]
    public IActionResult Edit(Employee model)
    {
        if (ModelState.IsValid && _employees.ContainsKey(model.Id))
        {
            _employees[model.Id] = model;
            return RedirectToAction("Index");
        }
        return View(model);
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        if (_employees.ContainsKey(id))
        {
            return View(_employees[id]);
        }
        return NotFound();
    }

    [HttpPost]
    public IActionResult Delete(Employee model)
    {
        if (_employees.ContainsKey(model.Id))
        {
            _employees.Remove(model.Id);
            return RedirectToAction("Index");
        }
        return NotFound();
    }

    public IActionResult Details(int id)
    {
        if (_employees.ContainsKey(id))
        {
            return View(_employees[id]);
        }
        return NotFound();
    }
}

Lab01Ak/Views/Shared/CustomError.cshtml
@{
    ViewBag.Title = "Błąd";
    Layout = "_Layout";
}

<h2>Błąd kalkulatora: @ViewBag.ErrorMessage</h2>

Lab01Ak/Views/Shared/CustomError02.cshtml
@{
    ViewBag.Title = "Błąd op";
    Layout = "_Layout";
}

<h2>Błąd kalkulatora: @ViewBag.ErrorMessage2</h2>

Lab01Ak/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab01Ak</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab01Ak.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab01Ak</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Birth</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab01Ak - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>